import { Product } from './types';

export const WHOLESALE_DISCOUNT = 0.18; // 18% discount for wholesale

// Company info
export const COMPANY = {
  name: 'Entre Cafés Colombianos',
  legalName: 'Entre Cafés Colombianos SAS',
  tagline: 'Specialty Colombian Coffee Exporters',
  slogan: 'From Colombian highlands to your cup',
  regions: 'Huila · Pereira · Santa Marta (seasonal)',
  altitude: '1,500+ MASL',
  scaScore: '84+ SCA',
  flavorProfile: 'Caramel · Chocolate · Red fruits',
  process: 'Fully washed',
  certification: 'INVIMA Certified',
  registroSanitario: 'NSA – 0006451-2019',
  contact: {
    name: 'David Leonardo Ramírez Contreras',
    email: 'cafecolombiano888@proton.com',
    country: 'Colombia',
    city: 'Bogotá D.C.',
  },
  social: {
    instagram: '',
    linkedin: '',
    whatsapp: '',
  },
};

export const PRODUCTS: Product[] = [
  {
    id: 'green-excelso',
    name: 'Green Coffee — Excelso UGQ',
    description: 'Unroasted Colombian green coffee, Excelso grade, screen size 14+. Sourced from specialty farms in Huila and Pereira at 1,500+ MASL. Washed process, moisture 11–12%, score 84+ SCA. Perfect for roasters seeking a clean, balanced specialty profile with notes of caramel, chocolate and red fruits.',
    origin: 'Huila · Pereira (regional sourcing)',
    roastLevel: 'green',
    price: 9.50,
    wholesaleDiscount: WHOLESALE_DISCOUNT,
    image: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=600&h=600&fit=crop',
    stock: 500,
    weight: '500g',
    active: true,
    flavorNotes: ['Caramel', 'Chocolate', 'Red Fruits'],
    altitude: '1,500+ MASL',
    process: 'Washed',
  },
  {
    id: 'roasted-medium',
    name: 'Medium Roast — Whole Bean',
    description: 'Whole bean Colombian coffee, medium roast level. Sourced from specialty farms in Huila and Pereira at 1,500+ MASL, washed process and roasted to highlight a balanced sweetness. Caramel and milk chocolate forward with a soft red fruit acidity.',
    origin: 'Huila · Pereira (regional sourcing)',
    roastLevel: 'medium',
    price: 13.50,
    wholesaleDiscount: WHOLESALE_DISCOUNT,
    image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=600&h=600&fit=crop',
    stock: 200,
    weight: '250g',
    active: true,
    flavorNotes: ['Caramel', 'Milk Chocolate', 'Red Fruits'],
    altitude: '1,500+ MASL',
    process: 'Washed',
  },
  {
    id: 'roasted-medium-high',
    name: 'Medium-High Roast — Whole Bean',
    description: 'A deeper, fuller-bodied expression of our regional blend. Roasted slightly longer to bring out chocolate intensity while preserving the bright caramel sweetness and red fruit finish. Excellent for espresso and stovetop methods.',
    origin: 'Huila · Pereira (regional sourcing)',
    roastLevel: 'medium-high',
    price: 14.50,
    wholesaleDiscount: WHOLESALE_DISCOUNT,
    image: 'https://images.unsplash.com/photo-1611854779393-1b2da9d400fe?w=600&h=600&fit=crop',
    stock: 180,
    weight: '250g',
    active: true,
    flavorNotes: ['Dark Chocolate', 'Caramel', 'Cherry'],
    altitude: '1,500+ MASL',
    process: 'Washed',
  },
  {
    id: 'ground-medium',
    name: 'Ground Coffee — Medium Roast',
    description: 'Freshly ground medium roast Colombian coffee, ready for filter, pour-over or moka pot brewing. Same regional blend as our whole bean offering, ground for convenience while preserving the caramel, chocolate and red fruit profile.',
    origin: 'Huila · Pereira (regional sourcing)',
    roastLevel: 'medium',
    price: 13.90,
    wholesaleDiscount: WHOLESALE_DISCOUNT,
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&h=600&fit=crop',
    stock: 150,
    weight: '250g',
    active: true,
    flavorNotes: ['Caramel', 'Chocolate', 'Soft Berry'],
    altitude: '1,500+ MASL',
    process: 'Washed',
  },
  {
    id: 'wholesale-green-bulk',
    name: 'Green Coffee — Bulk (Wholesale)',
    description: 'Bulk green coffee for roasters and importers. Excelso UGQ minimum, washed process, score 84+ SCA. Standard packaging in 70 kg jute bags or 30 kg GrainPro liners. Available CIF Europe ports. Minimum order: 250 kg samples or 1,000 kg commercial. Pricing on request based on origin lot, volume and Incoterm.',
    origin: 'Huila · Pereira · Santa Marta (seasonal)',
    roastLevel: 'green',
    price: 0,
    wholesaleDiscount: 0,
    image: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=600&h=600&fit=crop',
    stock: 10000,
    weight: '1 kg (price on request)',
    active: true,
    flavorNotes: ['Caramel', 'Chocolate', 'Red Fruits'],
    altitude: '1,500+ MASL',
    process: 'Washed',
  },
];

// Target export markets
export const EXPORT_MARKETS = [
  { code: 'BE', name: 'Belgium' },
  { code: 'SE', name: 'Sweden' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'DE', name: 'Germany' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'ZA', name: 'South Africa' },
];

// Kept for legacy AuthModal compatibility (Dutch retail clients).
export const DUTCH_PROVINCES = [
  'Drenthe',
  'Flevoland',
  'Friesland',
  'Gelderland',
  'Groningen',
  'Limburg',
  'Noord-Brabant',
  'Noord-Holland',
  'Overijssel',
  'Utrecht',
  'Zeeland',
  'Zuid-Holland',
];

export const ROAST_LABELS: Record<string, string> = {
  green: 'Green (Unroasted)',
  medium: 'Medium Roast',
  'medium-high': 'Medium-High Roast',
  decaf: 'Decaffeinated',
};
