import { Product } from './types';

export const WHOLESALE_DISCOUNT = 0.18; // 18% discount for wholesale

// Company info
export const COMPANY = {
  name: 'Colombian Coffee Huila',
  tagline: 'We are farming families',
  slogan: 'From our farm directly to your coffee cup',
  farm: 'Finca El Jardín',
  location: 'El Gigante, Huila, Colombia',
  origin: 'El Gigante – Huila, Colombia',
  altitude: '1,750 masl',
  roaster: 'AyP Tostadores',
  certification: 'INVIMA Certified',
  registroSanitario: 'NSA – 0006451-2019',
  contact: {
    name: 'Juan David Solorza',
    phone: '+31 6 8279 9885',
    email: 'info@huilacoffee.nl',
    country: 'The Netherlands',
    city: 'The Hague',
    address: 'Waldorpstraat 1282',
    postalCode: '2521 CJ',
  },
};

export const PRODUCTS: Product[] = [
  {
    id: 'castillo-medium',
    name: 'Castillo Medium Roast',
    description: 'A balanced and smooth Colombian coffee from the Castillo variety, cultivated at 1,750 meters in Finca El Jardín, El Gigante – Huila. Picked by hand by local farming families, carefully dried and roasted preserving its aroma, smoothness and unique flavor. From our farm directly to your coffee cup.',
    origin: 'Finca El Jardín, El Gigante – Huila',
    roastLevel: 'medium',
    price: 12.50,
    wholesaleDiscount: WHOLESALE_DISCOUNT,
    image: '/products/castillo-medium-high.png',
    stock: 150,
    weight: '125g',
    active: true,
    flavorNotes: ['Caramel', 'Citrus', 'Brown Sugar'],
    altitude: '1,750 masl',
    process: 'Washed',
  },
  {
    id: 'castillo-medium-high',
    name: 'Castillo Medium-High Roast',
    description: 'A fuller-bodied expression of the Castillo variety with a deeper roast profile. Cultivated at 1,750 meters in Finca El Jardín, El Gigante – Huila, picked by hand by local farming families and carefully roasted. Rich chocolate and nutty undertones with a subtle smoky finish.',
    origin: 'Finca El Jardín, El Gigante – Huila',
    roastLevel: 'medium-high',
    price: 13.50,
    wholesaleDiscount: WHOLESALE_DISCOUNT,
    image: '/products/castillo-medium-high.png',
    stock: 120,
    weight: '125g',
    active: true,
    flavorNotes: ['Dark Chocolate', 'Walnut', 'Smoky'],
    altitude: '1,750 masl',
    process: 'Washed',
  },
  {
    id: 'bourbon-papayo',
    name: 'Bourbon Papayo',
    description: 'An exceptional specialty coffee from the rare Bourbon Papayo variety. Grown at 1,750 meters in Finca El Jardín, El Gigante – Huila, this honey-processed coffee delivers a complex cup with tropical fruit notes, floral aromatics, and a honey-like sweetness that lingers.',
    origin: 'Finca El Jardín, El Gigante – Huila',
    roastLevel: 'medium',
    price: 18.90,
    wholesaleDiscount: WHOLESALE_DISCOUNT,
    image: '/products/bourbon-papayo.png',
    stock: 80,
    weight: '125g',
    active: true,
    flavorNotes: ['Tropical Fruit', 'Honey', 'Floral', 'Papaya'],
    altitude: '1,750 masl',
    process: 'Honey',
  },
  {
    id: 'decaf',
    name: 'Decaf Colombian Coffee',
    description: 'All the flavor, none of the caffeine. Our decaf blend from Finca El Jardín in El Gigante – Huila is cultivated at 1,750 meters by local farming families. Picked by hand, carefully dried and roasted preserving its aroma, smoothness and unique flavor.',
    origin: 'Finca El Jardín, El Gigante – Huila',
    roastLevel: 'decaf',
    price: 14.50,
    wholesaleDiscount: WHOLESALE_DISCOUNT,
    image: '/products/decaf.png',
    stock: 100,
    weight: '125g',
    active: true,
    flavorNotes: ['Milk Chocolate', 'Caramel', 'Soft Fruit'],
    altitude: '1,750 masl',
    process: 'Washed',
  },
  {
    id: 'green-coffee',
    name: 'Green Coffee Beans',
    description: 'Premium unroasted green coffee beans from Finca El Jardín, El Gigante – Huila. Sourced directly from farming families at 1,750 meters, these beans offer full control over the roasting process. From our farm directly to your coffee cup.',
    origin: 'Finca El Jardín, El Gigante – Huila',
    roastLevel: 'green',
    price: 8.90,
    wholesaleDiscount: WHOLESALE_DISCOUNT,
    image: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=600&h=600&fit=crop',
    stock: 200,
    weight: '500g',
    active: true,
    flavorNotes: ['Versatile', 'Full Potential', 'Raw'],
    altitude: '1,750 masl',
    process: 'Washed / Natural',
  },
];

export const DUTCH_PROVINCES = [
  'Drenthe',
  'Flevoland',
  'Friesland',
  'Gelderland',
  'Groningen',
  'Limburg',
  'Noord-Brabant',
  'Noord-Holland',
  'Overijssel',
  'Utrecht',
  'Zeeland',
  'Zuid-Holland',
];

export const ROAST_LABELS: Record<string, string> = {
  green: 'Green (Unroasted)',
  medium: 'Medium Roast',
  'medium-high': 'Medium-High Roast',
  decaf: 'Decaffeinated',
};
